---
- name: Set up New Relic infrastructure monitoring
  become: true
  import_role:
    name: newrelic.newrelic_install
  vars:
    targets:
      - infrastructure
  environment:
    NEW_RELIC_API_KEY: "{{ newrelic_api_key }}"
    NEW_RELIC_ACCOUNT_ID: "{{ newrelic_account_id }}"
  when:
    - newrelic_api_key | default('') | length > 0
