sshguard_block_time: 120
sshguard_detection_time: 1800
sshguard_threshold: 30
sshguard_config_items:
- sshguard.conf
- allowlist
sshguard_config_path: /etc/sshguard
# Full path to backend executable
sshguard_backend: /usr/lib/x86_64-linux-gnu/sshg-fw-nft-sets
# Shell command that provides logs on standard output. Example: ssh and sendmail from systemd journal:
sshguard_logreader: "LANG=C /bin/journalctl -afb -p info -n1 -o cat SYSLOG_FACILITY=4 SYSLOG_FACILITY=10"
sshguard_whitelist:
- comment: IPv4 localhost
  address: 127.0.0.0/8
- comment: IPv6 localhost
  address: ::1
